# fly.toml app configuration file generated for zenix on 2023-11-03T15:21:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zenix"
primary_region = "arn"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[metrics]
  port = 4000
  path = "/metrics"
  
[mount]
  source = "grafana_storage"
  destination = "/var/lib/grafana"
